package com.starempires.phases;

public enum Phase {

    UNLOAD_SHIPS,
    DEPLOY_DEVICES,
    LOAD_SHIPS,
    MAP_REMOVE_OBJECTS,
    MAP_MOVE_OBJECTS,
    MAP_ADD_OBJECTS,
    MAP_MODIFY_OBJECTS,
    ADD_KNOWN_ITEMS,
    REMOVE_KNOWN_ITEMS,
    MAP_DRIFT_OBJECTS,
    STABILIZE_PORTALS,
    COLLAPSE_PORTALS,
    DISSIPATE_NEBULAE,
    FLUCTUATE_STORMS,
    GENERATE_STORMS,
    DISSIPATE_STORMS,
    SELF_DESTRUCT_SHIPS,
    FIRE_GUNS,
    APPLY_COMBAT_DAMAGE,
    REMOVE_DESTROYED_SHIPS_I,
    AUTO_REPAIR_SHIPS,
    DETERMINE_OWNERSHIP_I,
    TRANSMIT_PORTAL_NAV_DATA,
    MOVE_SHIPS,
    TRAVERSE_PORTALS,
    ACQUIRE_NAV_DATA,
    WEATHER_STORMS,
    REMOVE_DESTROYED_SHIPS_II,
    DETERMINE_OWNERSHIP_II,
    RELOCATE_HOMEWORLDS,
    ESTABLISH_INTERDICTIONS,
    ESTABLISH_BLOCKADES,
    SALVAGE_DESIGNS,
    CREATE_DESIGNS,
    GIVE_DESIGNS,
    BUILD_SHIPS,
    REPAIR_SHIPS,
    TOGGLE_TRANSPONDER_MODES,
    CONCEAL_SHIPS,
    IDENTIFY_SHIPS,
    PRODUCE_RESOURCE_UNITS,
    POOL_RESOURCE_UNITS,
    TRANSFER_RESOURCE_UNITS,
    DENY_SCAN_ACCESS,
    AUTHORIZE_SCAN_ACCESS,
    COLLECT_SCAN_DATA,
    SHARE_SCAN_DATA,
    RECORD_NEW_MAP_OBJECTS;

    @Override
    public String toString() {
        String s = name().toLowerCase();
        s = s.replaceAll("_", " ");
        s = s.replaceAll("ii$", "II");
        s = s.replaceAll("i$", "I");
        return s;
    }

}
